### ISSUE TITLE
Cant open application on mac.

### ISSUE THREAD

**Issue by MustarEske** [Aarav2709/Needlelight#2]
### Lumafly Version

v.5.1.0.1

### Hollow Knight Version

It doesnt even open

### Steps to Reproduce

When trying to open Lumafly, it gives this message "The application “Lumafly” can’t be opened."

### Expected Behaviour

The program to open

### Actual Behaviour

It didnt

### Errors and Logs

<img width="353" height="255" alt="Image" src="https://github.com/user-attachments/assets/f4fdb8c6-b153-4d85-8e96-b6aa8de5fce7" />

**Comment by Aarav2709** [comment]
i'm not sure about mac os, i'll fix it, i need some time to recover from some personal problems.

**Comment by Aarav2709** [comment]
i have fixed it, i'll release, once i fix the other bug as well.

**Comment by MustarEske** [comment]
Im still getting the error. It still looks the same in side of Macos folder.

<img width="761" height="155" alt="Image" src="https://github.com/user-attachments/assets/e27cbb2e-7272-4e89-bc2f-38884c9039c3" />

**Comment by MustarEske** [comment]
When i run LumaflyV2 from this folder, <img width="526" height="348" alt="Image" src="https://github.com/user-attachments/assets/a6581c2a-575b-44eb-9fd3-e104b49ab742" /> it shows this in terminal: <img width="603" height="380" alt="Image" src="https://github.com/user-attachments/assets/849423d2-292b-4605-99ab-df0f01880742" /> But the app never launches.

**Comment by Aarav2709** [comment]
Thanks for this, I'll fix it tomorrow.

**Comment by Aarav2709** [comment]
please check v5.1.0.4, @Endy3032, @Hyperactiveman and @MustarEske. 
also, please, give your opinion -> https://github.com/Aarav2709/LumaflyV2/discussions/8 !

**Comment by Endy3032** [comment]
i made a pr that fixes the macos build

the script that built the app had a line that was mistakenly unindented which wrote the executable to the wrong location, should be fixed when pr #9 is merged and the app is rebuilt

**Comment by Aarav2709** [comment]
Alright, thanks a lot Endy, I'll review, and merge it. Thanks a lot. Also, if you want to, would you like to be a collaborator for MacOS versions?

**Comment by Aarav2709** [comment]
pls check, i have merged it.

**Comment by Aarav2709** [comment]
v6.0.0.0 will be released next week, as i have to prepare for my birthday this week, sorry for the delay :( meanwhile, use https://github.com/Endy3032/LumaflyV2/actions/runs/17888226376 macos users!

**Comment by Endy3032** [comment]
> Alright, thanks a lot Endy, I'll review, and merge it. Thanks a lot. Also, if you want to, would you like to be a collaborator for MacOS versions?

i can't really help with code as i don't know C#, but if you need testing or ask stuff about the macos build feel free to message me

also i think it could be beneficial if you also contribute upstream if possible, as i'm pretty sure people are still more likely to use the official lumafly app, just my 2 cents

**Comment by Aarav2709** [comment]
@Endy3032 , please try if you can fix the macos version, v6.0.0.0, also guys, please check https://github.com/Aarav2709/Needlelight/issues/10 for latest updates. v5.1.0.1 won't be entertained anymore!
